# Use https://dependabot.com/docs/config-file/validator/ to check for errors.
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gomod"
    directory: "/benchmarks/aes"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/benchmarks/chained-function-serving"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/benchmarks/chained-function-eventing"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/utils/tracing/go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/tools/invoker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/tools/deployer"
    schedule:
      interval: "weekly"

  # Enable version updates for Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
