apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/fibonacci-go:latest
          imagePullPolicy: Always
          ports:
            - name: h2c
              containerPort: 50051
