apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-adservice
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=9555
            - --function-name=adservice
            - --generator=unique
            - --value=donuts
        - image: docker.io/vhiveease/onlineshop-adservice:latest
          env:
          - name: PORT
            value: "9555"