apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-checkoutservice
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/kn-checkoutservice:latest
          imagePullPolicy: Always
          ports:
            - name: h2c
              containerPort: 50051