apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-cartservice
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/kn-cartservice:latest
          imagePullPolicy: Always
          ports:
            - name: h2c
              containerPort: 50051