apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-emailservice
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=8080
            - --function-name=emailservice
            - --generator=unique
        - image: docker.io/vhiveease/onlineshop-emailservice:latest
          env:
          - name: PORT
            value: "8080"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"