version: "3.9"
services:

  paymentservice:
    image: vhiveease/onlineshop-paymentservice:latest
    container_name: 'paymentservice'
    build:
      context: ./../../paymentservice/
      dockerfile: ./Dockerfile
    environment:
      - PORT=50051
    entrypoint: [ "node", "index.js" ]
    ports:
    - target: 50051

  relay:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50000
      - --function-endpoint-url=paymentservice
      - --function-endpoint-port=50051
      - --function-name=paymentservice
      - --generator=unique
      - --value=100
    ports:
      - published: 50000
        target: 50000