version: "3.9"
services:

  paymentservice:
    image: vhiveease/onlineshop-paymentservice:latest
    container_name: 'paymentservice'
    build:
      context: ./../../paymentservice/
      dockerfile: ./Dockerfile
    environment:
      - PORT=50051
    entrypoint: [ "node", "index.js" ]
    ports:
    - published: 8086
      target: 50051
    restart: always
    cpuset: "0-6"

