version: "3.9"
services:

  shippingservice:
    image: vhiveease/onlineshop-shippingservice:latest
    container_name: 'shippingservice'
    build:
      context: ./../../shippingservice/
      dockerfile: ./Dockerfile
    environment:
      - PORT=50051
    entrypoint: ["/shippingservice"]
    ports:
    - published: 8089
      target: 50051
    restart: always
    cpuset: "0-6"

